// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTour: typeof import('@nutui/nutui-taro')['Tour']
    NutTrendArrow: typeof import('@nutui/nutui-taro')['TrendArrow']
    NutWatermark: typeof import('@nutui/nutui-taro')['Watermark']
  }
}
