// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutAvatarGroup: typeof import('@nutui/nutui')['AvatarGroup']
    NutBadge: typeof import('@nutui/nutui')['Badge']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutPagination: typeof import('@nutui/nutui')['Pagination']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
