// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutRange: typeof import('@nutui/nutui')['Range']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
