// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutElevator: typeof import('@nutui/nutui')['Elevator']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutMenu: typeof import('@nutui/nutui')['Menu']
    NutMenuItem: typeof import('@nutui/nutui')['MenuItem']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutStep: typeof import('@nutui/nutui')['Step']
    NutSteps: typeof import('@nutui/nutui')['Steps']
    NutSwipe: typeof import('@nutui/nutui')['Swipe']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
