export default {
  pages: [
    'pages/index/index',
    'pages/button/index',
    'pages/collapse/index',
    'pages/layout/index',
    'pages/backtop/index',
    'pages/actionsheet/index',
    'pages/toast/index',
    'pages/notify/index',
    'pages/picker/index',
    'pages/datepicker/index',
    'pages/cell/index',
    'pages/uploader/index',
    'pages/icon/index',
    'pages/price/index',
    'pages/checkbox/index',
    'pages/swiper/index',
    'pages/avatar/index',
    'pages/popup/index',
    'pages/dialog/index',
    'pages/radio/index',
    'pages/overlay/index',
    'pages/infiniteloading/index',
    'pages/range/index',
    'pages/drag/index',
    'pages/steps/index',
    'pages/navbar/index',
    'pages/tabbar/index',
    'pages/inputnumber/index',
    'pages/input/index',
    'pages/switch/index',
    'pages/rate/index',
    'pages/calendar/index',
    'pages/shortpassword/index',
    'pages/textarea/index',
    'pages/address/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
