// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutEcard: typeof import('@nutui/nutui')['Ecard']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutPullRefresh: typeof import('@nutui/nutui')['PullRefresh']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTour: typeof import('@nutui/nutui')['Tour']
    NutTrendArrow: typeof import('@nutui/nutui')['TrendArrow']
    NutWatermark: typeof import('@nutui/nutui')['Watermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
