// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCalendar: typeof import('@nutui/nutui')['Calendar']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutComment: typeof import('@nutui/nutui')['Comment']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutDrag: typeof import('@nutui/nutui')['Drag']
    NutEcard: typeof import('@nutui/nutui')['Ecard']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutProgress: typeof import('@nutui/nutui')['Progress']
    NutPullrefresh: typeof import('@nutui/nutui')['Pullrefresh']
    NutPullRefresh: typeof import('@nutui/nutui')['PullRefresh']
    NutRate: typeof import('@nutui/nutui')['Rate']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTour: typeof import('@nutui/nutui')['Tour']
    NutTrendArrow: typeof import('@nutui/nutui')['TrendArrow']
    NutVideo: typeof import('@nutui/nutui')['Video']
    NutWatermark: typeof import('@nutui/nutui')['Watermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
