// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
  }
}
