// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCalendar: typeof import('@nutui/nutui')['Calendar']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCircleProgress: typeof import('@nutui/nutui')['CircleProgress']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutDrag: typeof import('@nutui/nutui')['Drag']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutNotify: typeof import('@nutui/nutui')['Notify']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutPrice: typeof import('@nutui/nutui')['Price']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRate: typeof import('@nutui/nutui')['Rate']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
