// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    NutButton: typeof import("@nutui/nutui")["Button"];
    NutEcard: typeof import("@nutui/nutui")["Ecard"];
    NutOverlay: typeof import("@nutui/nutui")["Overlay"];
    NutPopup: typeof import("@nutui/nutui")["Popup"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
