// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
