// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAddress: typeof import('@nutui/nutui-taro')['Address']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutNumberKeyboard: typeof import('@nutui/nutui-taro')['NumberKeyboard']
    NutPopover: typeof import('@nutui/nutui-taro')['Popover']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRange: typeof import('@nutui/nutui-taro')['Range']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
