/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
  }
}
