// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAddress: typeof import('@nutui/nutui')['Address']
    NutAddressList: typeof import('@nutui/nutui')['AddressList']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutBadge: typeof import('@nutui/nutui')['Badge']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCategory: typeof import('@nutui/nutui')['Category']
    NutCategoryPane: typeof import('@nutui/nutui')['CategoryPane']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
    NutComment: typeof import('@nutui/nutui')['Comment']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutEllipsis: typeof import('@nutui/nutui')['Ellipsis']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutIndicator: typeof import('@nutui/nutui')['Indicator']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutList: typeof import('@nutui/nutui')['List']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutNotify: typeof import('@nutui/nutui')['Notify']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRange: typeof import('@nutui/nutui')['Range']
    NutRate: typeof import('@nutui/nutui')['Rate']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutSku: typeof import('@nutui/nutui')['Sku']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    NutUploader: typeof import('@nutui/nutui')['Uploader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanButtton: typeof import('vant/es')['Buttton']
  }
}
