// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutSwitch: typeof import('@nutui/nutui')['Switch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
