// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Actionsheet: typeof import('./src/components/actionsheet.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    copy: typeof import('./src/components/layout copy.vue')['default']
    Drag: typeof import('./src/components/drag.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutAudio: typeof import('@nutui/nutui')['Audio']
    NutAudioOperate: typeof import('@nutui/nutui')['AudioOperate']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutDrag: typeof import('@nutui/nutui')['Drag']
    NutImagepreview: typeof import('@nutui/nutui')['Imagepreview']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutPrice: typeof import('@nutui/nutui')['Price']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    Price: typeof import('./src/components/price.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
